### PR TITLE
WL-3753 Removed username from the subject line in the forum

### PR DESCRIPTION
**Pull request by ouit0408**
notification message. This pull request is linked to https://github.com/ox-it/wl-docker/pull/4

### CODE REVIEW

**Comment by nicholaswilson100** [comment]
Isn't this just adding a space?

**Comment by ouit0408** [comment]
you mean adding space , review comment suggested to add space after : , hence the change.

**Comment by nicholaswilson100** [comment]
ok

**Comment by nicholaswilson100** [comment]
where's the comment?

**Comment by ouit0408** [comment]
https://jira.oucs.ox.ac.uk/jira/browse/WL-3753

**Pull request merged**
